### PR TITLE
Amend version on installation page

### LINKED ISSUE #85: Bump to the most recent version on installation page
Currently 1.6.0

### PR DESCRIPTION
**Pull request by juanjovazquez**
closes #85

### CODE REVIEW

**Comment by etorreborre** [comment]
👍

**Comment by etorreborre** [comment]
@jcranky please approve

**Comment by etorreborre** [comment]
Thanks @juanjovazquez !

**Comment by juanjovazquez** [comment]
@etorreborre You're welcome. Just a minor thing to motivate myself for getting deeper into grafter ;-)

**Pull request merged**
