### PR TITLE
Add method `replacedWith`

### LINKED ISSUE #108: Report the success of `replace`
At the moment the `replace` method returns the application graph with no indication of the success of the replacement. We could add a method `replaceAtLeastOnce` which would return `Option[Application]` with `None` as a result if nothing was replaced.

### PR DESCRIPTION
**Pull request by danielkarch**
Closes #108

`oldThing.replaceOrFail(s)` returns Some(newThing) if replacing with `s` was successful,
or `None` otherwise.

@etorreborre @jcranky Is that the sort of thing you had in mind?

### CODE REVIEW

**Comment by etorreborre** [comment]
That looks all good to me. I am just wondering if the name could be `replacedWith` instead of `replaceOrFail` so that we write `g.replacedWith(s)` to get, or not, a replaced `g`.

**Comment by danielkarch** [comment]
Sure, I was also unhappy with the name. I will change it. 

For some reason codacy complains about "Usage of `get` on optional type" on `if (rewriter.successfullyReplaced.get) Some(newGraph) else None`, but that's `AtomicBoolean#get` ...

**Comment by etorreborre** [comment]
👍

**Comment by etorreborre** [comment]
@danielkarch nice Codacy bug :-)

**Comment by etorreborre** [comment]
Thanks Daniel for this PR!

**Comment by danielkarch** [comment]
👍

**Comment by danielkarch** [comment]
Arrr, I cannot approve PRs in the zalando org any more. ^^

**Comment by jcranky** [comment]
That is a good start. But instead of being binary, perhaps we could keep track of what was replaced, some that we can know more than if something was replaced or not. We could know exactly what was replaced, for cases when just one object was replaced and you expected two replacements, or something like that.

**Comment by etorreborre** [comment]
I think both methods would be useful. In the second case we probably need:
```
// something like that I didn't check the types
def replaceWith(s: S): OptionT[Writer, S, T]
```
to finally get a result like `Option[(T, List[S])]`.

But let's proceed with this method and open a PR for another one.

**Comment by jcranky** [comment]
:+1:

**Comment by danielkarch** [comment]
Codacy was still complaining. I changed the `AtomicBoolean` to a boolean `var`, there is actually no reason to not do that.

**Comment by jcranky** [comment]
Not sure if a `var` is much better, and codacy will now complain about the `var`. Codacy is an option check afaik though, so we can use common sense here :)

**Comment by etorreborre** [comment]
I wonder if there's a way to make Codacy a bit less whining. I'll try to have a look at that later. In the meantime I realized something cool. Even if `replacedWith` returns an `Option` it should be possible to chain calls:
```scala
val app: Option[Application] = 
  application
    .replacedWith[HttpClient](client)
    .replacedWith[CatalogService](service)
```

Just because `None` will not be replaced with anything.

**Comment by danielkarch** [comment]
@jcranky a `var` is perfectly safe here, so I prefer it to the `AtomicBoolean`. But yes, codacy is still complaining. The tool is obviously not smart enough to tell you anything interesting about the code quality. Do you *have* to use it?

**Comment by jcranky** [comment]
@danielkarch The fact that it has false negative is not a demerit. Using a `var` is an exception and being warned about it is good. I'll try to make this one as ignored.

**Comment by jcranky** [comment]
:+1:

**Comment by etorreborre** [comment]
👍

**Pull request merged**
