### PR TITLE
Add link to an application template

### PR DESCRIPTION
**Pull request by jcranky**
Said template will generate a fully setup grafter application
with http4s.

### CODE REVIEW

**Comment by jcranky** [comment]
:+1:

**Comment by etorreborre** [comment]
👍

**Comment by etorreborre** [comment]
A few comments on the template. I would:

 - rather use annotations instead of `genericReader`
 - rather use `.start` instead of `Rewriter.start`
 - use `singletons` to show the configuration of application components
 - replace `httpServer` by `httpServerConfig` to avoid confusion

**Comment by jcranky** [comment]
@etorreborre thanks for feedback on the template, I'll address them :)

**Comment by jcranky** [comment]
@etorreborre I did the change to use annotations: https://github.com/jcranky/grafter-http4s.g8/commit/bcb200dc705981ce70b828220960f3411a6305fa - interesting fact: the compilation times for the generated project with the annotations is about 50% _faster_ then the previous version

**Pull request merged**
