### PR TITLE
Tweak the component creation documentation a bit

### PR DESCRIPTION
**Pull request by jcranky**
I don't want to change this one too much yet. but my impression is that having an explicit `reader` is sometimes optional and this could be mentioned. In some experimentations I noted that if a given dependency is a `case class` that only contains other `case class`es, you don't need to create the `reader` function due to shapeless magic.

### CODE REVIEW

**Comment by etorreborre** [comment]
You mean that in that case it is only necessary to declare a `reader` for an interface?

**Comment by jcranky** [comment]
@etorreborre sort of - I mean that you only need a `reader` for the top level component. But in my experiment I used `case class`es straight away, with no formal component interfaces.

**Comment by etorreborre** [comment]
That's interesting. I would like to understand more about all of that and the impacts in terms of:

 - code evolution: is there a moment where you need to suddenly add readers everywhere because you change something?

 - compilation speed: do you just need one `genericReader` call at the top level, instead of having annotations on each components? If you don't declare readers on each components but only call `genericReader` where you use them (in tests for example) what are the penalties in terms of compilation speed?

**Comment by etorreborre** [comment]
👍

**Comment by jcranky** [comment]
@etorreborre good points, I'll investigate that, later. The second point is a good one, I have the impression that yes, the compilation times were worse than they should be

**Pull request merged**
