### PR TITLE
Show attributes in dot graphs. fixes #94

### LINKED ISSUE #94: Visualize components attributes
It would be nice to be able to display attributes when [producing an application graph](https://github.com/zalando/grafter/blob/master/doc/inspect-app-graph.md).

Typically we can show as attributes any case class member which is not a dependency itself. For examples "configuration" case classes members fall in that category:
```
@reader
case class HttpServer(config: HttpServerConfig)

case class HttpServerConfig(host: String, port: Int)
```
Then we should see `host` and `port` printed in the `.dot` graph for the `HttpServer`.

### PR DESCRIPTION
**Pull request by etorreborre**
Review @jcranky 

I had a go at tinbox and the results look good.

### CODE REVIEW

**Comment by danielkarch** [comment]
Pretty cool! 👍 
But should we have Zalando-internal host names etc. on public GitHub?

**Comment by jcranky** [comment]
@danielkarch which host names are you talking about here?

**Comment by jcranky** [comment]
:+1:

**Comment by danielkarch** [comment]
Look at the application graph pasted above.

**Comment by jcranky** [comment]
Ah, I see it now. I didn't notice the... details. I'll edit them out.

**Pull request merged**
