### PR TITLE
Improve readers macro

### LINKED ISSUE #118: Configuration with type parameters
I have some external components, that I can't really create through grafter's functionality (they are created by an `fs2.Stream`).

I had the idea to add some kind of context case class to my configuration, with the "external" dependencies. However, doing it this way requires a type parameter in my config class (`case class Config[F[_]](...)`), which gives this error:

```
[error] ...: A1 takes no type parameters, expected: one
[error] @readers
```

Should I just not do it this way? If not, is there a way to do something like this?

### PR DESCRIPTION
**Pull request by aeons**
This PR adds the ability to have higher order types as the target of `@readers` macro.

I'm basically stumbling around in the dark here, so would love someone to take a look at it. 
As far as I can tell it does what I need it to do for my use case, but I'm not sure if it makes other things harder to do.

This fixes #118 

I also upgraded some dependencies, let me know if you want me to put that in a separate PR.

### CODE REVIEW

**Comment by etorreborre** [comment]
This looks ok to me but I would be even more convinced with tests! Can you please add some examples showing that the macro is doing what we want?

**Comment by etorreborre** [comment]
Sorry for closing I meant to comment...

**Comment by aeons** [comment]
Testing macros hurts my head.

The test I added compiles. Is that enough? It's just copy/pasting from some of the existing tests.

**Comment by aeons** [comment]
Not sure the CI failure is due to these changes.

**Comment by etorreborre** [comment]
Ok I updated your PR, let's see how it goes.

**Comment by etorreborre** [comment]
I have no idea what's going on with travis and sbt, still not working.

**Comment by etorreborre** [comment]
👍

**Comment by etorreborre** [comment]
Ok apparently I had to nuke the travis caches, all good now it's merged I will publish a new release soon.

**Comment by etorreborre** [comment]
Available [here](https://oss.sonatype.org/content/repositories/releases/org/zalando/grafter_2.12/2.6.0/)

**Pull request merged**
