### PR TITLE
#71 compile docs with tut

### PR DESCRIPTION
**Pull request by alodavi**
Solved #71

### CODE REVIEW

**Comment by jcranky** [comment]
Nice :)
What triggers the doc compilation? Do you have to manually do it or does it get compile with src compilation?

**Comment by etorreborre** [comment]
Thanks @alodavi :-). It looks like some setting is missing to run tut on the files in `doc`. I think that something like `tutSourceDirectory := file("doc")` is necessary in the build.sbt but apparently not enough. When running `tut:doc` we should see some files in `target/scala-2.12/tut` but I don't see them. Also if there's any compiler error in the `.md` files `tut` should tell us. Can you please play with the settings and see what works?

**Comment by alodavi** [comment]
@jcranky unfortunately I noticed that it doesn't compile. I thought that the default settings would have been enough
Alright @etorreborre ! Let me check if I can fix this problem

**Comment by LappleApple** [comment]
Nice to see you here, @alodavi  :)

**Comment by alodavi** [comment]
@LappleApple hello! :)

**Comment by alodavi** [comment]
Ok, now it's compiling :) try to run "tut" from the sbt console and then check the target/scala-2.12/tut folder to see the docs ;)

**Comment by jcranky** [comment]
@alodavi thanks! 
Now, when I tried to run it locally I got lots of error like:

```scala
<console>:13: error: illegal start of simple expression
val app: Application =
^
[tut] *** Error reported at /tmp/grafter/doc/singletons.md:67
<console>:12: error: not found: type Application
       val app1: Application =
```

Also, can we perhaps have a test to assure that the docs compilation works? This way we could make it always sure to not merge broken documentation :)

**Comment by alodavi** [comment]
@jcranky I'm not sure if this is what you want, but I handled exceptions due to e.g. pseudocode by passing modifiers (as suggested in the tut readme)

**Comment by etorreborre** [comment]
@alodavi I think the best would be to add the missing imports to make the code compile :-).

**Comment by alodavi** [comment]
@etorreborre sure, but it seems that I always get this `warning: Unused import `and this `error: No warnings can be incurred under -Xfatal-warnings `. From what I read it something that has to do with the fact that Tut does not filter out `-Ywarn-unused-imports` from its `scalacOptions` anymore. 

I'm trying to use something like this
`scalacOptions in Tut := (scalacOptions in Tut).value.filterNot(Set("-Ywarn-unused-import"))`
but it didn't solve the problem

**Comment by etorreborre** [comment]
@alodavi so you're saying that the tut docs fail without the imports and show unused imports with the imports?

**Comment by alodavi** [comment]
@etorreborre well, it actually fail even if the imports are there. E.g. in boilerplate.md we have 
`import org.zalando.grafter.GenericReader._`, the console will display 
`<console>:12: warning: Unused import
       import org.zalando.grafter.GenericReader.genericReader`
and then `<console>:13: error: not found: type Reader
         implicit def readerHttpConfig: Reader[ApplicationConfig, HttpConfig] =`
`<console>:14: error: not found: value genericReader
           genericReader
           ^`
`tut:silent:fail ` shows code that doesn't compile, without showing the compilation error. But I don't think that silencing tut is a good solution in this case. I would rather understand why the compiler is ignoring imports

**Comment by etorreborre** [comment]
@alodavi can you please do a sanity check to verify if this is a tut shortcoming or just some non-compiling code?
For example this "boilerplate.md-like" code compiles ok
```scala
  import org.zalando.grafter.GenericReader._
  import cats.data.Reader

  case class DbConfig()
  case class HttpConfig()

  case class ApplicationConfig(db:   DbConfig,
                               http: HttpConfig)
  object ApplicationConfig {
    implicit def readerHttpConfig: Reader[ApplicationConfig, HttpConfig] =
      genericReader

    implicit def readerDbConfig: Reader[ApplicationConfig, DbConfig] =
      genericReader
  }
```
Does it also compile with tut?

**Comment by alodavi** [comment]
@etorreborre after some checks I found out that this code snippet just doesn't compile in tut... The problem is due to the fact that the imports are ignored by tut. I'm checking if it has to do with tut dependencies.

**Comment by etorreborre** [comment]
Sorry Aloisia, I finally got to use it, leveraging specs2 for this which I know well enough to be fast.
Don't worry there are still [ambitious issues to solve](https://github.com/zalando/grafter/issues/2) :-).

**Pull request closed without merging**
