### PR TITLE
Macro to replace genericReader boilerplate

### PR DESCRIPTION
**Pull request by shanethehat**
It is very common to require a companion object that just provides an implicit Reader from the genericReader 

```scala
object PostgresDatabase {
  implicit def reader: Reader[ApplicationConfig, PostgresDatabase] = genericReader
}
```

This PR adds a new macro annotation so that this companion object can be omitted. Instead, the case class should be annotated with the `@reader` annotation, supplying a type parameter that is to be used as the first type parameter of the Reader:

```scala
@reader[ApplicationConfig]
case class PostgresDatabase(dbConfig: DbConfig) extends Start {
```

### CODE REVIEW

**Comment by etorreborre** [comment]
👍  that's really cool, thanks!

**Comment by etorreborre** [comment]
👍

**Comment by etorreborre** [comment]
I just published `1.3.0`.

**Comment by shanethehat** [comment]
@etorreborre Awesome, thank you!

**Pull request merged**
