### PR TITLE
Update readme with maintenance notice

### PR DESCRIPTION
**Pull request by perploug**
Notice on the readme outlining when the project will go into maintenance mode and who to reach out to if anyone wants to drive this project forward

Signed-off-by: Per Ploug <per.ploug@zalando.de>

### CODE REVIEW

**Comment by jcranky** [comment]
thanks

**Comment by jcranky** [comment]
:+1:

**Comment by etorreborre** [comment]
Can we mention that I will maintain the project at http://github.com/etorreborre/grafter?

**Comment by perploug** [comment]
Sorry for the delay in this - updated the text with a link to the fork

**Comment by perploug** [comment]
👍

**Pull request merged**
